// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Penguin.Persistence.Database.ConnectionString.Test(System.String)~Penguin.Persistence.Database.ConnectionString.TestResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Penguin.Persistence.Database.Extensions.DataTableExtensions.GetSingle``1(System.Data.DataTable,System.Boolean)~``0")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Penguin.Persistence.Database.ConnectionString.TestResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Penguin.Persistence.Database.ConnectionString.connectionString")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Penguin.Persistence.Database.Objects.DatabaseInstance.ExecuteToDictionary(System.String,System.Object[])~System.Collections.Generic.Dictionary{System.String,System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Penguin.Persistence.Database.TypeConverter.Find(System.Type)~Penguin.Persistence.Database.TypeConverter.DbTypeMapEntry")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Penguin.Persistence.Database.TypeConverter.Find(System.Data.SqlDbType)~Penguin.Persistence.Database.TypeConverter.DbTypeMapEntry")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Penguin.Persistence.Database.TypeConverter.Find(System.Data.DbType)~Penguin.Persistence.Database.TypeConverter.DbTypeMapEntry")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~F:Penguin.Persistence.Database.ConnectionType.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Penguin.Persistence.Database.Helpers.ScriptHelpers.RunSplitScript(System.String,System.String,System.Int32,System.String,System.Text.Encoding,System.Boolean,System.Int32)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Penguin.Persistence.Database.Objects.DatabaseInstance.Backup(System.String,System.String,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Penguin.Persistence.Database.Objects.DatabaseInstance.Restore(System.String,System.String,System.Text.Encoding)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:Penguin.Persistence.Database.Helpers.ScriptHelpers.DEFAULT_SPLIT")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Penguin.Persistence.Database.Helpers.ScriptHelpers.RunSplitScript(System.IO.Stream,System.String,System.Int32,System.String,System.Text.Encoding,System.Boolean,System.Int32)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Penguin.Persistence.Database.Objects.DatabaseInstance.ExecuteScript(System.String,System.String,System.Text.Encoding,System.Boolean,System.Int32)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Penguin.Persistence.Database.Objects.DatabaseInstance.Restore(System.String,System.String,System.Int32,System.String,System.Text.Encoding)~System.Threading.Tasks.Task")]